image: Visual Studio 2022
platform:
  - amd64

build_script:
   - ps: |  # Builds a dynamic library, as some languages like python only support dynamic libraries.
      cmake -B build -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED=ON
      cmake --build build

artifacts:
  - path: 'build\RLBotBM.dll'