image: Visual Studio 2022
platform:
  - amd64

build_script:
   - ps: |  # Builds a dynamic library, as some languages like python only support dynamic libraries. IPO is set to off to be safe
      cmake -B build_dynamic -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DBUILD_DLL=ON -DDENABLE_IPO=OFF
      cmake --build build_dynamic
      cmake -B build -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DDENABLE_IPO=OFF
      cmake --build build

artifacts:
  - path: 'build_dynamic\RLBot-BM.dll'
    name: 'RLBot-BM_dynamic.dll'
  - path: 'build\RLBot-BM.lib'
    name: 'RLBot-BM.lib'